### ISSUE TITLE
Use ArrayAccessor trait

### ISSUE THREAD

**Issue by shadowhand** [mugnate/oauth2-ecwid#1]
The [`ArrayAccessor` trait](https://github.com/thephpleague/oauth2-client/blob/2.0.0/src/Tool/ArrayAccessorTrait.php) can be used instead of [`isset` calls](https://github.com/mugnate/oauth2-ecwid/blob/e67175e51bfd9621ae034d0f8304e9b3f767f6b6/src/Provider/EcwidStoreProfile.php#L33).

**Comment by votintsev** [comment]
@shadowhand Thanks! Great improvement!
